Repository GSG-CF04/team05-to-DO, pull requests merged in 2021-11, with the labels that each got.

#3 create file structure
  index.html
  todo.css
  todo.js
Labels: approved

#8 wrote README file
  README.md
Labels: documentation, approved

#7 created header and toggle button
  index.html
  todo.css
  todo.js
Labels: approved

#13 added live link to the readme file
  README.md
Labels: approved

#14 write html and css file for input add section
  index.html
  todo.css
Labels: approved

#18 addSectionTaske
  index.html
  todo.css
  todo.js
Labels: approved

#21 change the section taske
  index.html
  todo.css
  todo.js
Labels: approved

#17 added full darkmode functionality including local storage
  index.html
  todo.css
  todo.js
Labels: awaiting-review

#22 Create Add Function , get to do and saveToLocalstorge
  index.html
  todo.js
Labels: awaiting-review

#25 sectionStayle
  todo.css
Labels: awaiting-review

#26 removeFinction
  todo.js
Labels: awaiting-review

#27 editFunction
  todo.js
Labels: awaiting-review

#28 add media for desktop and tablet
  todo.css
Labels: approved
